### ISSUE TITLE
Bugs PHP

### ISSUE THREAD

**Issue by marcioyonamine** [marcioyonamine/igsis#40]
http://centrocultural.cc/igsis/visual/index.php?perfil=contratos&p=frm_edita_pj&&id_pj=1

Notice: Undefined index: idRepresentante02 in /var/www/igsis/perfil/m_contratos/frm_edita_pj.php on line 109

-----------------------------------------------------------

**Comment by LoreleiGab** [comment]
Não consegui duplicar o Representante Legal do Contratados para m_contratos/frm_edita_pj.php

**Comment by marcioyonamine** [comment]
sobe lá no server para eu dar uma olhada.

**Comment by LoreleiGab** [comment]
Ao cadastrar um representante legal que não existia

Link: 
http://www.centrocultural.cc/igsis/visual/index.php?perfil=contratos&p=frm_cadastra_propostapj&id_ped=

Erro:
Warning: Illegal string offset 'IdProponente' in /var/www/igsis/perfil/m_contratos/frm_cadastra_propostapj.php on line 193

Warning: Illegal string offset 'idEvento' in /var/www/igsis/perfil/m_contratos/frm_cadastra_propostapj.php on line 195

Warning: Illegal string offset 'IdExecutante' in /var/www/igsis/perfil/m_contratos/frm_cadastra_propostapj.php on line 197

Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given in /var/www/igsis/funcoes/funcoesSiscontrat.php on line 174

**Comment by marcioyonamine** [comment]
as linhas para inserir estão na página do pedido ainda. já vejo isso.
