### ISSUE TITLE
Recupera Representante Legal

### ISSUE THREAD

**Issue by LoreleiGab** [marcioyonamine/igsis#74]

**Comment by LoreleiGab** [comment]
Os relatórios do módulo Contratos não estão retornando os representantes legais

**Comment by marcioyonamine** [comment]
esse já foi?

**Comment by LoreleiGab** [comment]
Sim

Enviado pelo meu Windows Phone
________________________________
De: Marcio Yonamine<mailto:notifications@github.com>
Enviada em: ‎27/‎11/‎2015 08:17
Para: marcioyonamine/igsis<mailto:igsis@noreply.github.com>
Cc: Lorelei Gabriele<mailto:loreleigab@hotmail.com>
Assunto: Re: [igsis] Recupera Representante Legal (#74)

esse já foi?

---
